### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by yfpchen** [cchen-cc/SIFA#13]
Hello, thank you for your effort. I made the following errors in training:
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_5_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 1, current size 0)
[[node shuffle_batch (defined at \document\second paper\code\SIFA-SIFA-v1\SIFA-SIFA-v1\data_loader.py:84) ]]

**Comment by cchen-cc** [comment]
This type of error usually happens when data cannot be correctly read. 
There can be various causes for why data are not read correctly and usually careful debugging is needed. 
Usually you could check the following things:
- whether the data paths stored in imagea_list and imageb_list are correct
- whether the data written into the tfrecords are with correct shape and type
- whether the data reading in the data_load.py is with correct shape and type

**Comment by yfpchen** [comment]
Hello, do you write each volume data image and label slice into the same tfrecord, or separately into the respective tfrecord? For example, do you write the images and labels corresponding slices in each CT_train's 16 volume dataset into the same xx.tfrecord or different tfrecord (e.g., xx1.tfrecord, xx2.tfrecord...1, xx16.tfrecord)? Looking forward to your reply. Thank you very much.

**Comment by cchen-cc** [comment]
Each tfrecord file only contain three consecutive slices of a CT volume. 
The format of each tfrecord file can refer to data_loader.py.

**Comment by Real-YeJ** [comment]
@cchen-cc  hey, author,  that is to say, if a nii file has 9 slices, I need to convert it to tfrecords three times, and 3 slices each time?

**Comment by cchen-cc** [comment]
If a nii file has 9 slices, you can convert it to 9 tfrecords files.

**Comment by Real-YeJ** [comment]
@cchen-cc one slice one tfrecords when training, and one slice one .nii file when evaluating, right?

**Comment by cchen-cc** [comment]
During data preprocessing, three consecutive slices are saved in one tfrecords, but during training, only the middle slice is used. 
When evaluating, one .nii file containing hundreds of slices in one CT/MR volume was converted into .npz format to input into evaluate.py.
