### ISSUE TITLE
d_loss_P and prediction

### ISSUE THREAD

**Issue by lfxuan** [cchen-cc/SIFA#23]
Hello! I am very interested in your work, but encountered some problems, (1) d_loss_P did not get the downward curve in the paper, but fell after rising. Why does this happen? (2) The prediction results of the model I trained have changed a lot. What causes it? How to obtain stable results? (3) The saved segmented image is black and white. How do I get the color-annotated image in the paper?Looking forward to your reply！

**Comment by cchen-cc** [comment]
d_loss_p generally decreases. The slight upward trend at the beginning may be because the unstable training at the beginning or some artifacts introduced with the moving average operation. 
Adversarial training is not as stable as supervised training with ground truth label, as the generator and discriminator compete with each other. 
You can make the gray-scale image to three channels and replace corresponding pixels with the RGB color value.
