### ISSUE TITLE
trained model request

### ISSUE THREAD

**Issue by pray5959** [cchen-cc/SIFA#32]
Hi, if it's convenient to share the trained model ? Thank you very much.

**Comment by cchen-cc** [comment]
Hi, the trained models can be downloaded from  https://www.dropbox.com/sh/787kmmuhvh3e3yb/AAC4qxBJTWwQ1UMN5psrN96ja?dl=0.

Note that for adaptation from cardiac MR to CT, set USE_newstat=False to get the same results as in the paper. This is because we re-calculate the data statistics before releasing the dataset. Using new data statics to train can get better results than our reported models, but to evaluate our trained model, we need to use the previously calculated one.
