### ISSUE TITLE
Some questions about trade off parameters

### ISSUE THREAD

**Issue by SakurajimaMaiii** [cchen-cc/SIFA#46]
Hi, thanks for your excellent work. I have 2 questions.
**a)** When training, trade -off paramenters : \lambad^{cycle} is equal to 10. but in the [https://github.com/cchen-cc/SIFA/blob/be5b792ecb7ed85f533bbb91223a7278e969b12d/main.py#L189](url) i.e. main.py  line 189. 
        seg_loss_B = ce_loss_b + dice_loss_b + l2_loss_b + 0.1 * (ce_loss_b_ll + dice_loss_b_ll) + 0.1 * g_loss_B + 0.1 * lsgan_loss_p + 0.01 * lsgan_loss_p_ll + 0.1 * lsgan_loss_a_aux
**why g_loss_b is multiplied by 0.1**?  
 if we set \lambda_{seg} is equal to 1, \lambda_{cyc} is to 10. In fatc, in seg_loss_B, the weight of cycle loss is equal to seg_loss...
**b)** It seems like that the output channels of discriminator_aux is 2. Why ? disA and disA_aux shoule have same layers and weight, i.e. it is the same network.
Thanks for your help.

**Comment by cchen-cc** [comment]
Hi，
a) \lambda_{cyc} is 10 for training the decoder U. g_loss_b is multiplied by 0.1 for training encoder E since encoder E also receives supervision from the segmentation loss. 
2) discriminator_aux has two tasks. It first needs to differentiate whether the inputs are real images or generated images. It also needs to differentiate whether the generated images are translated from real target images or reconstructed from the translated target images.

**Comment by wangm-ting** [comment]
> Hi，
> a) \lambda_{cyc} is 10 for training the decoder U. g_loss_b is multiplied by 0.1 for training encoder E since encoder E also receives supervision from the segmentation loss.
> 2) discriminator_aux has two tasks. It first needs to differentiate whether the inputs are real images or generated images. It also needs to differentiate whether the generated images are translated from real target images or reconstructed from the translated target images.
请问discriminator_aux的两个返回值分别是什么

**Comment by cchen-cc** [comment]
The first output of discriminator_aux is for the differentiation of real images and generated images. 
The second output is for the differentiation of the images translated from real target images and the reconstructed images.
